  #Embedded port number
server:
     port: 4343
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/Reports
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 1729
   jpa:
     hibernate:
       ddl-auto: update
     properties:
        hibernate:
             format_sql: true
     show-sql: true    
   
